- name: CREATING THE K8S WORKSTATION
  hosts: all
  become: yes

  

  tasks:
  - name: Install Python 3
    yum:
      name: python3
      state: present

  - name: Install pip
    yum:
      name: python3-pip
      state: present

  - name: Install boto3 and botocore libraries
    pip:
      name:
        - boto3
        - botocore
      state: present
      executable: pip3
  - name: ensure bucket is created
    vars:
        ansible_python_interpreter: /usr/bin/python3
        aws_access_key: "{{ lookup('env', 'mys3user') }}"
        aws_secret_key: "{{ lookup('env', 'YgY6A1@Q') }}"
    s3_bucket:
      name: sindhu123456
      state: present
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
    environment:
      KOPS_STATE_STORE: s3://k8-project-10001

...
